### PR TITLE
Treat non-zero exit code as error + fix all tests

### PR DESCRIPTION
**Pull request by radeksimko**
I can split this into multiple PRs if necessary.

I don't think that git-lint should only rely on standard output/error when it comes to error detection, it should also check and respect exit codes.

Thanks a lot for making this tool! :smiley_cat:

### CODE REVIEW

**Comment by radeksimko** [comment]
btw. latest pylint is broken on Python 3.2 and upstream doesn't seem to care, so I intentionally used older version for testing in Travis, see https://bitbucket.org/logilab/pylint/issue/408/pylint-does-not-work-on-python-32-after

**Comment by sk-** [comment]
@radeksimko Thanks for the PR. I wrote some comments.

As a summary I think we could integrate the last 3 commits. The second commit may not be necessary as I think it was just a matter of using the wrong tidy version (old one vs tidy-html5). The first commit I think will add some noise as now all messages with no severity will be flagged as errors.

**Comment by radeksimko** [comment]
I think I will cherry pick some commits off this PR and create separate PRs to make it easier for reviewing.

**Comment by sk-** [comment]
Thanks! Will be waiting for them.

**Comment by sk-** [comment]
I already fixed the tests in Travis. So feel free to cherry pick your changes.

**Comment by sk-** [comment]
I integrated some of the changes. Closing for now.

**Pull request closed without merging**
