### PR TITLE
Add settings to lint R files

### PR DESCRIPTION
**Pull request by freedryk**
R is a little weird because lintr only runs from within the R REPL, so you have to run R and load the lintr package to lint a file.

### CODE REVIEW

**Comment by freedryk** [comment]
Sigh, tests.  I'll try fixing this over the weekend.

**Comment by stianlagstad** [comment]
Hi @freedryk! Is this something that you might keep working on? :)

**Comment by freedryk** [comment]
@stianlagstad not much more I can do on this, it's ready to merge but nobody seems to want it :)

**Comment by sk-** [comment]
I added it to the list of recipes https://github.com/sk-/git-lint/wiki/Linter-Recipes. For the time being I am not accepting new linters, or otherwise the project is going to bloat testing all the potential linters.

I will need to think of a way of having the linter recipes in their own repos, so that they can be maintained independently. The idea would be to have some default config and then add something like

```
git lint add-linter github.com/user/linter-recipe
```

**Pull request closed without merging**
